### ISSUE TITLE
table.py should generate table data in a format required for the application

### ISSUE THREAD

**Issue by roikle** [CSBP-CPSE/lode-viewer#23]
**Issue:** Currently the table.py creates a collection of table data files (CSV files which are saved as JSON files). The table.js code, is structured to take CSV files to display table data, but consequently a number of limitations exist due to the data being stored in a CSV structure, and not a more descriptive JSON structure. See below for current issues; 

1. CSV data currently needs to be reprocessed every-time a page of table data is shown in the viewer application, to provide localization of the strings for specific fields (e.g. provide the English or French versions of a facility type or prov/terr name). This post processing would be better performed as a preprocess step and the en/fr strings for a table column could be stored in each of the data files if the data was structured as a JSON file. 
2. Due to the nature of the data being stored in CSV, the field names currently need to be in the same order as it's stored in the table data. If we used a JSON structure, it would be much easier/quicker to re-organize the table row order to whatever a developer wants. 
3. Filtering out columns of data in the table would be easier if the table data was stored in a dictionary data structure. 
4. Lastly storing the data in the expected file format will reduce confusion for future developers. 

Any additional suggestions/comments @Noznoc?

**Comment by Noznoc** [comment]
Makes sense to me, I am just not sure if Bruno intentionally had it as csv structure for any other reason. Please dev this on a branch and maybe we can test it with Dissemination sooner rather than later as we wait for data from AGRI?
